# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [2]:
import numpy as np

In [4]:
np.zeros(100, int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 2.Создать вектор размера 100, заполненный единицами

In [5]:
np.ones(100, int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### 3.Создать вектор размера 100, заполненный числом 3

In [6]:
np.full(100, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 5. Поменять 2 строки в матрице

In [18]:
matrix = np.arange(1, 26).reshape(5, 5)
print(matrix)
print()
matrix[[0, 2]] = matrix[[2, 0]]
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[[11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [16 17 18 19 20]
 [21 22 23 24 25]]


#### 6. Создать вектор со значениями от 10 до 100

In [16]:
vector = np.arange(10, 101)
print(vector)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


#### 7. Развернуть вектор (первый становится последним)

In [ ]:
vector = np.arange(10, 101)

#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [20]:
matrix = np.arange(16).reshape(4, 4)
print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

#### 10. Создать 3x3 единичную матрицу

In [22]:
np.identity(3, int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 11. Создать массив 3x3x3 со случайными значениями

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

#### 14. Создать матрицу с 0 внутри, и 1 на границах

#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

#### 20. Перемножить матрицы 5x3 и 3x2

#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

#### 24. Есть генератор, сделать с его помощью массив

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

#### 26. Отсортировать вектор

#### 27. Проверить, одинаковы ли 2 numpy массива

#### 28. Сделать массив неизменяемым

#### 29. Найти n наибольших значений в массиве

#### 30. Заменить максимальный элемент на ноль

#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

#### 34. Напечатать все значения в массиве

#### 35. Найти ближайшее к заданному значению число в заданном массиве

#### 36. Преобразовать массив из float в int

#### 37. Каков эквивалент функции enumerate для numpy массивов?

#### 38. Случайно расположить p элементов в 2D массив

#### 39. Отнять среднее из каждой строки в матрице

#### 40. Отсортировать матрицу по n-ому столбцу

#### 41. Определить, есть ли в 2D массиве нулевые столбцы

#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям