# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [37]:
import numpy as np

In [38]:
np.zeros(100, int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 2.Создать вектор размера 100, заполненный единицами

In [39]:
np.ones(100, int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### 3.Создать вектор размера 100, заполненный числом 3

In [40]:
np.full(100, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [41]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 5. Поменять 2 строки в матрице

In [42]:
matrix = np.arange(1, 26).reshape(5, 5)
print(matrix)
print()
matrix[[0, 2]] = matrix[[2, 0]]
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[[11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [16 17 18 19 20]
 [21 22 23 24 25]]


#### 6. Создать вектор со значениями от 10 до 100

In [43]:
vector = np.arange(10, 101)
print(vector)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


#### 7. Развернуть вектор (первый становится последним)

In [44]:
vector = np.array([1, 2, 3, 4, 5], int)
print(vector[::-1])

[5 4 3 2 1]


#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [45]:
matrix = np.arange(16).reshape(4, 4)
print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [67]:
vector = np.array([1, 2, 3, 4, 5], int)
new_vector = np.array([vector[i // 4] if i % 4 == 0 else 0 for i in range(4 * len(vector)-3)], int)
print(new_vector)


[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 10. Создать 3x3 единичную матрицу

In [47]:
np.identity(3, int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 11. Создать массив 3x3x3 со случайными значениями

In [71]:
np.random.random(27).reshape(3, 3, 3)

array([[[0.46606172, 0.11852241, 0.47355114],
        [0.92765785, 0.58496569, 0.87369579],
        [0.75855147, 0.41160024, 0.84449519]],

       [[0.40366307, 0.96844725, 0.81139895],
        [0.02045279, 0.26888542, 0.3137961 ],
        [0.63425132, 0.88395903, 0.982484  ]],

       [[0.65931086, 0.21595233, 0.4836744 ],
        [0.72510083, 0.41433425, 0.25237224],
        [0.32519281, 0.62098614, 0.76320911]]])

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [74]:
matrix = np.random.random(100).reshape(10, 10)
print(matrix)
print('Min:', matrix.min())
print('Max:', matrix.max())

[[0.60871982 0.97259557 0.53911802 0.09987321 0.00770518 0.47163721
  0.3479687  0.56933747 0.85984928 0.32979542]
 [0.18926682 0.86579764 0.3333217  0.90678877 0.03421165 0.74648665
  0.76195471 0.87638844 0.5637065  0.22604969]
 [0.74698516 0.48685027 0.93253358 0.23205906 0.12086054 0.36156668
  0.5825675  0.46696527 0.53463025 0.34360496]
 [0.59795498 0.43963454 0.95729432 0.53718801 0.91001244 0.39173677
  0.64513624 0.80812062 0.48381978 0.38858739]
 [0.09590277 0.01707183 0.37968253 0.28291549 0.77893159 0.16439458
  0.20356593 0.19111011 0.1991922  0.08702271]
 [0.20371396 0.77529601 0.64113659 0.19806686 0.32689169 0.66544007
  0.94522694 0.61841644 0.90900014 0.0121554 ]
 [0.20170652 0.88879818 0.28914282 0.87720577 0.53910604 0.96164515
  0.49056982 0.36560296 0.97561471 0.08832234]
 [0.01203876 0.76730009 0.26838653 0.56802656 0.37495289 0.86076891
  0.95093386 0.2097826  0.45809507 0.39704068]
 [0.02451427 0.61279388 0.71017408 0.02374787 0.81300313 0.91870325
  0.9039986 

#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [75]:
vector = np.random.random(30)
print(vector)
print('Avg:', vector.mean())

[0.59443205 0.87097752 0.59678244 0.50063833 0.68776461 0.45405618
 0.17349318 0.75995859 0.68424398 0.77511874 0.14571175 0.57415876
 0.62023365 0.76658293 0.22570586 0.11934937 0.04278461 0.66355142
 0.3494272  0.37833042 0.71971665 0.45249541 0.91330255 0.79962047
 0.41261733 0.76457383 0.36411864 0.24925157 0.84758336 0.60320044]
Avg: 0.5369927272679293


#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [84]:
matrix = np.ones(25).reshape(5, 5)
matrix[1:-1, 1:-1] = 0
print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

In [111]:
matrix = np.eye(5, dtype=int)
print(matrix)
print('Транспонированная матрица:')
print(matrix.T)
print('Транспонированная матрица единичной матрицы эквивалентна самой единичной матрице')
print(matrix == matrix.T)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
Транспонированная матрица:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
Транспонированная матрица единичной матрицы эквивалентна самой единичной матрице
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [100]:
temp = np.diag(np.arange(1, 5), k=-1)
print(temp)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [117]:
matrix = np.zeros(64, dtype=int).reshape(8, 8)
matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1
print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [125]:
flat_matrix = 1 + np.arange(6*7*8)
print('Сотый элемент в одномерном массиве:', flat_matrix[100])
matrix = flat_matrix.reshape(6, 7, 8)
index = np.unravel_index(100, (6, 7, 8))
print('Индекс сотого элемента в трехмерном массиве:', index)
print('Его значение:', matrix[index])

Сотый элемент в одномерном массиве: 101
Индекс сотого элемента в трехмерном массиве: (1, 5, 4)
Его значение: 101


#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [127]:
vector = np.array([1, 0, 1, 0, 1, 0, 1, 0,   0, 1, 0, 1, 0, 1, 0, 1], int)
matrix = np.tile(vector, 4).reshape(8, 8)
print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Перемножить матрицы 5x3 и 3x2

In [134]:
m1 = 1 + np.arange(15).reshape(5, 3)
m2 = 1 + np.arange(6).reshape(3, 2)
print(m1)
print()
print(m2)
print()
print('Prod of m1 and m2:')
print(m1.dot(m2))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

[[1 2]
 [3 4]
 [5 6]]

Prod of m1 and m2:
[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [138]:
array = [-i if 3<i<8 else i for i in range(10)]
print(array)

[0, 1, 2, 3, -4, -5, -6, -7, 8, 9]


#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [142]:
temp = [0, 1, 2, 3, 4]
matrix = np.tile(temp, 5).reshape(5, 5)
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 24. Есть генератор, сделать с его помощью массив

In [144]:
# range - генератор
array = [i for i in range(10)]
print(array)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [145]:
vector = np.random.random(10)
print(vector)

[0.61888097 0.25168539 0.67058342 0.80773125 0.9148927  0.19282409
 0.31244816 0.83414196 0.74698854 0.10849677]


#### 26. Отсортировать вектор

In [148]:
vector = [np.random.randint(10) for i in range(10)]
print(vector)
vector.sort()
print(vector)

[4, 6, 7, 6, 9, 5, 5, 5, 2, 2]
[2, 2, 4, 5, 5, 5, 6, 6, 7, 9]


#### 27. Проверить, одинаковы ли 2 numpy массива

In [151]:
a = np.arange(5)
b = np.array([1, 2, 4, 12, 4], int)
c = np.arange(5)
print(a)
print(b)
print(c)
print(np.allclose(a, b), np.allclose(a, c))

[0 1 2 3 4]
[ 1  2  4 12  4]
[0 1 2 3 4]
False True


#### 28. Сделать массив неизменяемым

In [153]:
array = np.array([1, 2, 3, 4], int)
array.flags.writeable = False
array[1] = 4

ValueError: assignment destination is read-only

#### 29. Найти n наибольших значений в массиве

In [164]:
vector = np.array([np.random.randint(100) for i in range(10)], int)
print(vector)
n = int(input('Вdедите n: '))
print(np.sort(vector)[(len(vector)-n):])

[39  2 36 61 83 28 76 72 62 72]
Вdедите n: 3
[72 76 83]


#### 30. Заменить максимальный элемент на ноль

In [167]:
vector = np.array([np.random.randint(100) for i in range(10)], int)
print(vector)
max_index = vector.argmax()
vector[max_index] = 0
print(vector)

[25 77 20  2 66 64 89 28 19  8]
[25 77 20  2 66 64  0 28 19  8]


#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [168]:
matrix = np.zeros((10,10), [('x',float),('y',float)])
matrix['x'], matrix['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(matrix)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [169]:
a = np.arange(5)
b = np.arange(5) + 1.5
c = 1 / (a-b)
print(c)

[-0.66666667 -0.66666667 -0.66666667 -0.66666667 -0.66666667]


#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

#### 34. Напечатать все значения в массиве

In [170]:
vector = np.array([np.random.randint(100) for i in range(10)], int)
print(vector)

[33 18 69 24 81 48 19 43 18 86]


#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [173]:
vector = np.array([np.random.randint(100) for i in range(20)], int)
print(vector)
value = int(input('Введите значение: '))
temp = np.abs(vector-value)
print(temp)
print(vector[temp.argmin()])

[83 11 42 35 52 32  6 97 66 33 68 36 87  8 33 75 55  4 41 43]
Введите значение: 50
[33 39  8 15  2 18 44 47 16 17 18 14 37 42 17 25  5 46  9  7]
52


#### 36. Преобразовать массив из float в int

In [176]:
array_float = np.arange(10, dtype=np.float32)
print(array_float)
array_int = array_float.astype(np.int32, copy=False)
print(array_int)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 37. Каков эквивалент функции enumerate для numpy массивов?

#### 38. Случайно расположить p элементов в 2D массив

In [191]:
matrix = np.arange(25).reshape(5, 5)
print(matrix)
print()
flat_matrix = matrix.reshape(25)
np.random.shuffle(flat_matrix)
print(flat_matrix.reshape(5, 5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[ 9 20  6 13  3]
 [ 2 17 11 15 19]
 [16 23 12 22 18]
 [10 14  5  1  7]
 [21  4  8  0 24]]


#### 39. Отнять среднее из каждой строки в матрице

In [198]:
vector = np.array([np.random.randint(100) for i in range(25)], int).reshape(5, 5)
print(vector)
print()
mean = vector.mean()
print('Mean:', mean)
print()
print(vector-mean)

[[11 18 72 49 42]
 [ 9 15 57 62 39]
 [88 91 54 84 33]
 [27 44 88 51 63]
 [61 60 71 26 99]]

Mean: 52.56

[[-41.56 -34.56  19.44  -3.56 -10.56]
 [-43.56 -37.56   4.44   9.44 -13.56]
 [ 35.44  38.44   1.44  31.44 -19.56]
 [-25.56  -8.56  35.44  -1.56  10.44]
 [  8.44   7.44  18.44 -26.56  46.44]]


#### 40. Отсортировать матрицу по n-ому столбцу

In [203]:
matrix = np.random.randint(0,10,(3,3))
n = int(input())
print(matrix)
print(matrix[matrix[:,n].argsort()])

1
[[8 5 6]
 [8 8 6]
 [7 8 0]]
[[8 5 6]
 [8 8 6]
 [7 8 0]]


#### 41. Определить, есть ли в 2D массиве нулевые столбцы

#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [202]:
matrix = np.ones(3**4).reshape(3, 3, 3, 3)
print(matrix[-2:].sum())
sum = matrix.reshape(matrix.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

54.0
[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]
