In [79]:
import numpy as np

## Задание 1
Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:<br>

а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$

б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$

в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$

г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$

### а)

In [80]:
a = np.random.randint(0, 100, (4, 2))
b = np.random.randint(0, 100, (4, 2))
print('A:\n', a, '\n\n', 'B:\n', b, '\n')

try:
    c = a.dot(b)
    print('АB - определено')
    print(c)
except ValueError as er:
    print('АB - не определено')
    print(er)
    
print()    
try:
    c = b.dot(a)
    print('BA - определено')
    print(c)
except ValueError as er:
    print('BA - не определено')
    print(er)

A:
 [[97 27]
 [47 73]
 [67 37]
 [ 4 97]] 

 B:
 [[86 39]
 [93  5]
 [95 48]
 [61 78]] 

АB - не определено
shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

BA - не определено
shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)


### б)

In [81]:
a = np.random.randint(0, 100, (2, 5))
b = np.random.randint(0, 100, (5, 3))
print('A:\n', a, '\n\n', 'B:\n', b, '\n')

try:
    c = a.dot(b)
    print('АB - определено')
    print(c)
except ValueError as er:
    print('АB - не определено')
    print(er)
    
print()    
try:
    c = b.dot(a)
    print('BA - определено')
    print(c)
except ValueError as er:
    print('BA - не определено')
    print(er)

A:
 [[44 90 63 39 66]
 [35 50 87 59 60]] 

 B:
 [[52 46 15]
 [88 95 64]
 [41 65 79]
 [71 82 50]
 [ 5  0 37]] 

АB - определено
[[15890 17867 15789]
 [14276 16853 15768]]

BA - не определено
shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)


### в)

In [82]:
a = np.random.randint(0, 100, (8, 3))
b = np.random.randint(0, 100, (3, 8))
print('A:\n', a, '\n\n', 'B:\n', b, '\n')

try:
    c = a.dot(b)
    print('АB - определено')
    print(c)
except ValueError as er:
    print('АB - не определено')
    print(er)
    
print()    
try:
    c = b.dot(a)
    print('BA - определено')
    print(c)
except ValueError as er:
    print('BA - не определено')
    print(er)

A:
 [[76 57 30]
 [96 20 18]
 [79 78  5]
 [34 51 72]
 [85 65 46]
 [80 94 77]
 [ 1 39 57]
 [35 30 86]] 

 B:
 [[96  0 72 47 54 75 95 29]
 [38 63 11 16 32 18 25 80]
 [36 38 50 42 81 53 36 72]] 

АB - определено
[[10542  4731  7599  5744  8358  8316  9725  8924]
 [10624  1944  8032  5588  7282  8514 10268  5680]
 [10728  5104  6796  5171  7167  7594  9635  8891]
 [ 7794  5949  6609  5438  9300  7284  7097 10250]
 [12286  5843  9135  6967 10396  9983 11356 10977]
 [14024  8848 10644  8498 13565 11773 12722 15384]
 [ 3630  4623  3351  3065  5919  3798  3122  7253]
 [ 7596  5158  7150  5737  9816  7723  7171  9607]]

BA - определено
[[26282 28620 22792]
 [17334 12247 14644]
 [25443 22665 21089]]


### г)

In [83]:
a = np.random.randint(0, 100, (4, 4))
b = np.random.randint(0, 100, (4, 4))
print('A:\n', a, '\n\n', 'B:\n', b, '\n')

try:
    c = a.dot(b)
    print('АB - определено')
    print(c)
except ValueError as er:
    print('АB - не определено')
    print(er)
    
print()    
try:
    c = b.dot(a)
    print('BA - определено')
    print(c)
except ValueError as er:
    print('BA - не определено')
    print(er)

A:
 [[67 37 80 47]
 [58 30 42 40]
 [31  6 58 25]
 [99 60 51 53]] 

 B:
 [[87 72 16  2]
 [85 71 68 20]
 [51 59 53 79]
 [ 5 51 63 57]] 

АB - определено
[[13289 14568 10789  9873]
 [ 9938 10824  7714  6314]
 [ 6290  7355  5553  6189]
 [16579 17100 11706  8448]]

BA - определено
[[10699  5595 11014  7475]
 [13901  6883 14746  9595]
 [16303  8715 13661 10269]
 [10889  5513  9103  6871]]


## Задание 2
Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [84]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
print('A:\n', a, '\n\n', 'B:\n', b, '\n')
print('A + B =\n', a+b)
print()
print('AB =\n', a.dot(b))
print()
print('BA =\n', b.dot(a))

A:
 [[ 1 -2]
 [ 3  0]] 

 B:
 [[ 4 -1]
 [ 0  5]] 

A + B =
 [[ 5 -3]
 [ 3  5]]

AB =
 [[  4 -11]
 [ 12  -3]]

BA =
 [[ 1 -8]
 [15  0]]


## Задание 3
Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [85]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])
print('A:\n', a, '\n\n', 'B:\n', b, '\n\n', 'C:\n', c, '\n')
print('3A - 2B + 4C =\n', 3*a - 2*b + 4*c)

A:
 [[ 1  7]
 [ 3 -6]] 

 B:
 [[ 0  5]
 [ 2 -1]] 

 C:
 [[ 2 -4]
 [ 1  1]] 

3A - 2B + 4C =
 [[ 11  -5]
 [  9 -12]]


## Задание 4
Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [86]:
a = np.array([[4, 1], [5, -2], [2, 3]])
print('A:\n', a, '\n')
print('T:\n', a.T, '\n')
print('AT =\n', a.dot(a.T), '\n')
print('TA =\n', a.T.dot(a))

A:
 [[ 4  1]
 [ 5 -2]
 [ 2  3]] 

T:
 [[ 4  5  2]
 [ 1 -2  3]] 

AT =
 [[17 18 11]
 [18 29  4]
 [11  4 13]] 

TA =
 [[45  0]
 [ 0 14]]


## Задание 5
Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

### а)
$$
\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} =
a \cdot d - b \cdot c =
sinx \cdot sinx - (-cosx) \cdot cosx =
sin^2x + cos^2x = 1
$$


### б)

In [87]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print('Определитель =', np.linalg.det(a))

Определитель = 180.0


### в)

In [88]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Определитель =', round(np.linalg.det(a), 0))
print('Следовательно матрица вырожденная')

Определитель = -0.0
Следовательно матрица вырожденная


## Задание 6
Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [89]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
det = round(np.linalg.det(a), 0)
if det == 0:
    print('Определитель:', det)
    print('Матрица вырожденная, так как ее определитель равен нулю')

Определитель: 0.0
Матрица вырожденная, так как ее определитель равен нулю


## Задание 7
Найти ранг матрицы:

$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$

In [90]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
r = np.linalg.matrix_rank(a)
print(f'Ранг матрицы: {r}')

Ранг матрицы: 2
